# --- Datasource ---
quarkus.datasource.db-kind=mariadb
quarkus.datasource.jdbc.url=jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:appdb}
quarkus.datasource.username=${DB_USER:app}
quarkus.datasource.password=${DB_PASS:app_pw}
quarkus.jooq.dialect=MARIADB

# --- Hibernate: aus, damit Flyway das Schema steuert ---
quarkus.hibernate-orm.database.generation=none

# --- Flyway: an ---
quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=classpath:db/migration

# Wenn die DB schon existiert (ohne flyway_schema_history):
quarkus.flyway.baseline-on-migrate=true

